---
dependencies:
  - name: ui
    version: "1.0.0"
    repository: "file://../ui"

  - name: crawler
    version: "1.0.0"
    repository: "file://../crawler"

  - name: mongodb
    version: 8.0.9
    repository: https://charts.bitnami.com/bitnami

  - name: rabbitmq
    version: 7.5.1
    repository: https://charts.bitnami.com/bitnami
